### PR TITLE
Docker without sudo

### PR DESCRIPTION
**Pull request by vovagorodok**

### CODE REVIEW

**Comment by kuzm1ch** [comment]
Could you add a separate step to install and configure Docker(post-install steps, which is added in PR)  for Ubuntu/Debian(the most mass Linux distros).
Ref 
## Docker install 
```
comand one
comand wo
```
### Post install 
```
comand one
comand two
reboot 
```

 IMHO, https://docs.docker.com/engine/install/ubuntu/  official doc is too complex for regular users. There is an idea to keep it as simple as possible.

**Comment by vovagorodok** [comment]
> Could you add a separate step to install and configure Docker(post-install steps, which is added in PR) for Ubuntu/Debian(the most mass Linux distros). Ref
> ## Docker install
> 
> ```
> comand one
> comand wo
> ```
> 
> ### Post install
> 
> ```
> comand one
> comand two
> reboot 
> ```
> 
> IMHO, https://docs.docker.com/engine/install/ubuntu/ official doc is too complex for regular users. There is an idea to keep it as simple as possible.

done

**Comment by kuzm1ch** [comment]
thanks a lot, going to merge it

Could you rebase your changes on top of the new main branch? It was changed(force push), sorry for this.

**Comment by vovagorodok** [comment]
> thanks a lot, going to merge it
> 
> Could you rebase your changes on top of the new main branch? It was changed(force push), sorry for this.

ok

**Comment by vovagorodok** [comment]
Done

**Pull request merged**
